export const tech = [
	{ name: "HTML5", icon: "simple-icons:html5", color: "#E34F26" },
	{ name: "CSS3", icon: "simple-icons:css3", color: "#1572B6" },
	{ name: "JavaScript", icon: "simple-icons:javascript", color: "#F7DF1E" },
	// { name: "Python", icon: "simple-icons:python", color: "#3776AB" },
	// { name: "Dart", icon: "simple-icons:dart", color: "#0175C2" },
	{ name: "Go", icon: "simple-icons:go", color: "#00ADD8" },
	{ name: "Nodejs", icon: "simple-icons:nodedotjs", color: "#339933" },
	{ name: "TailwindCSS", icon: "simple-icons:tailwindcss", color: "#06B6D4" },
	// { name: "UnoCSS", icon: "simple-icons:unocss", color: "#333333" },
	{ name: "Svelte", icon: "simple-icons:svelte", color: "#FF3E00" },
	// { name: "Solidjs", icon: "simple-icons:solid", color:"#2C4F7C" },
	{ name: "Express", icon: "simple-icons:express", color: "#000000" },
	// { name: "Flutter", icon: "simple-icons:flutter", color: "#02569B" },
	{ name: "Prisma", icon: "simple-icons:prisma", color: "#2D3748" },
	// { name: "PlayWright", icon: "simple-icons:playwright", color:"#2EAD33" },
	// { name: "Vitest", icon: "simple-icons:vitest", color:"#6E9F18" },
	{ name: "Docker", icon: "simple-icons:docker", color: "#2496ED" },
	// { name: "SQLite", icon: "simple-icons:sqlite", color: "#003B57" },
	{ name: "MySQL", icon: "simple-icons:mysql", color: "#4479A1" },
	// { name: "PocketBase", icon: "simple-icons:pocketbase", color:"#B8DBE4" },
	{ name: "Git", icon: "simple-icons:git", color: "#F05032" },
	{ name: "GitHub", icon: "simple-icons:github", color: "#181717" },
];
