export default [
	{ name: "HTML5", icon: "simple-icons:html5" },
	{ name: "CSS3", icon: "simple-icons:css3" },
	{ name: "JavaScript(ES6+)", icon: "simple-icons:javascript" },
	// { name: "Python", icon: "simple-icons:python" },
	{ name: "Dart", icon: "simple-icons:dart" },
	// { name: "Go", icon: "simple-icons:go" },
	{ name: "Nodejs", icon: "simple-icons:nodedotjs" },
	{ name: "TailwindCSS", icon: "simple-icons:tailwindcss" },
	{ name: "UnoCSS", icon: "simple-icons:unocss" },
	// { name: "Sass", icon: "simple-icons:sass" },
	{ name: "Svelte(Kit)", icon: "simple-icons:svelte" },
	// { name: "Solidjs", icon: "simple-icons:solid" },
	{ name: "Express", icon: "simple-icons:express" },
	{ name: "Flutter", icon: "simple-icons:flutter" },
	{ name: "Markdown", icon: "simple-icons:markdown" },
	// { name: "EJS", icon: "file-icons:ejs" },
	// { name: "Socket.io", icon: "simple-icons:socketdotio" },
	{ name: "Prisma", icon: "simple-icons:prisma" },
	{ name: "Mongoose", icon: "arcticons:letter-lowercase-m" },
	// { name: "PlayWright", icon: "simple-icons:playwright" },
	// { name: "Jest", icon: "simple-icons:jest" },
	// { name: "Vitest", icon: "simple-icons:vitest" },
	{ name: "Vite", icon: "simple-icons:vite" },
	// { name: "Esbuild", icon: "simple-icons:esbuild" },
	{ name: "Thunder Client", icon: "mdi:thunder-circle" },
	// { name: "Docker", icon: "simple-icons:docker" },
	// { name: "Strapi", icon: "simple-icons:strapi" },
	{ name: "SQLite", icon: "simple-icons:sqlite" },
	// { name: "MySQL", icon: "simple-icons:mysql" },
	{ name: "MongoDB", icon: "simple-icons:mongodb" },
	// { name: "PocketBase", icon: "simple-icons:pocketbase" },
	{ name: "Git", icon: "simple-icons:git" },
	{ name: "GitHub", icon: "simple-icons:github" },
	{ name: "Netlify", icon: "simple-icons:netlify" },
	{ name: "Vercel", icon: "simple-icons:vercel" },
	{ name: "Render", icon: "simple-icons:render" },
];
